In [ ]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('../data/processed/master_2017plus.csv')

In [7]:
df_master = pd.read_csv('../data/processed/master_features.csv')

In [6]:
df.head()

,date,region,wind_mu,hydro_mu,solar_mu,total_renewable_mu,day_of_week,month,quarter,day_of_year,...,wind_mu_dev_from_avg,solar_mu_day_change_pct,wind_mu_day_change_pct,total_renewable_mu_day_change_pct,solar_mu_cv7,wind_mu_cv7,total_renewable_mu_cv7,vre_ratio,re_7d_trend,failure
0,2017-08-01,ER,0.0,109,1.1,110.1,1,8,3,213,...,0.0,1.100000,0.0,0.019266,0.359300,0.0,0.024085,0.009901,0.089216,0
1,2017-08-02,ER,0.0,106,1.1,107.1,2,8,3,214,...,0.0,0.000000,0.0,-0.027003,0.408393,0.0,0.020671,0.010176,0.029524,0
2,2017-08-03,ER,0.0,105,0.3,105.3,3,8,3,215,...,0.0,-0.380952,0.0,-0.016651,0.382537,0.0,0.022059,0.002822,-0.015741,0
3,2017-08-04,ER,0.0,107,0.9,107.9,4,8,3,216,...,0.0,0.461538,0.0,0.024459,0.354945,0.0,0.021136,0.008264,-0.010000,0
4,2017-08-05,ER,0.0,109,0.7,109.7,5,8,3,217,...,0.0,-0.105263,0.0,0.016529,0.305555,0.0,0.022923,0.006323,0.015596,0

In [8]:
df_master.head()

,date,region,wind_mu,hydro_mu,solar_mu,total_renewable_mu,day_of_week,month,quarter,day_of_year,...,wind_mu_dev_from_avg,solar_mu_day_change_pct,wind_mu_day_change_pct,total_renewable_mu_day_change_pct,solar_mu_cv7,wind_mu_cv7,total_renewable_mu_cv7,vre_ratio,re_7d_trend,failure
0,2012-04-01,ER,0.0,16,0.0,16.0,6,4,2,92,...,0.0,NaN,NaN,NaN,0.0,0.0,0.000000,0.0,NaN,0
1,2012-04-02,ER,0.0,16,0.0,16.0,0,4,2,93,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,NaN,0
2,2012-04-03,ER,0.0,19,0.0,19.0,1,4,2,94,...,0.0,0.0,0.0,0.176471,0.0,0.0,0.096225,0.0,NaN,0
3,2012-04-04,ER,0.0,18,0.0,18.0,2,4,2,95,...,0.0,0.0,0.0,-0.050000,0.0,0.0,0.082192,0.0,NaN,0
4,2012-04-05,ER,0.0,20,0.0,20.0,3,4,2,96,...,0.0,0.0,0.0,0.105263,0.0,0.0,0.095152,0.0,NaN,0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9590 entries, 0 to 9589
Data columns (total 54 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   date                               9590 non-null   object
 1   region                             9590 non-null   object
 2   wind_mu                            9590 non-null   float64
 3   hydro_mu                           9590 non-null   int64
 4   solar_mu                           9590 non-null   float64
 5   total_renewable_mu                 9590 non-null   float64
 6   day_of_week                        9590 non-null   int64
 7   month                              9590 non-null   int64
 8   quarter                            9590 non-null   int64
 9   day_of_year                        9590 non-null   int64
 10  is_monsoon                         9590 non-null   int64
 11  is_summer                          9590 non-null   int64
 12  is_winter                          9590 non-null   int64
 13  month_sin                          9590 non-null   float64
 14  month_cos                          9590 non-null   float64
 15  solar_mu_lag1                      9590 non-null   float64
 16  solar_mu_lag3                      9590 non-null   float64
 17  solar_mu_lag7                      9590 non-null   float64
 18  solar_mu_lag14                     9590 non-null   float64
 19  wind_mu_lag1                       9590 non-null   float64
 20  wind_mu_lag3                       9590 non-null   float64
 21  wind_mu_lag7                       9590 non-null   float64
 22  wind_mu_lag14                      9590 non-null   float64
 23  hydro_mu_lag1                      9590 non-null   float64
 24  hydro_mu_lag3                      9590 non-null   float64
 25  hydro_mu_lag7                      9590 non-null   float64
 26  hydro_mu_lag14                     9590 non-null   float64
 27  total_renewable_mu_lag1            9590 non-null   float64
 28  total_renewable_mu_lag3            9590 non-null   float64
 29  total_renewable_mu_lag7            9590 non-null   float64
 30  total_renewable_mu_lag14           9590 non-null   float64
 31  solar_mu_roll7_mean                9590 non-null   float64
 32  solar_mu_roll30_mean               9590 non-null   float64
 33  solar_mu_roll7_std                 9590 non-null   float64
 34  wind_mu_roll7_mean                 9590 non-null   float64
 35  wind_mu_roll30_mean                9590 non-null   float64
 36  wind_mu_roll7_std                  9590 non-null   float64
 37  hydro_mu_roll7_mean                9590 non-null   float64
 38  hydro_mu_roll30_mean               9590 non-null   float64
 39  hydro_mu_roll7_std                 9590 non-null   float64
 40  total_renewable_mu_roll7_mean      9590 non-null   float64
 41  total_renewable_mu_roll30_mean     9590 non-null   float64
 42  total_renewable_mu_roll7_std       9590 non-null   float64
 43  solar_mu_dev_from_avg              9590 non-null   float64
 44  wind_mu_dev_from_avg               9590 non-null   float64
 45  solar_mu_day_change_pct            9590 non-null   float64
 46  wind_mu_day_change_pct             9590 non-null   float64
 47  total_renewable_mu_day_change_pct  9590 non-null   float64
 48  solar_mu_cv7                       9590 non-null   float64
 49  wind_mu_cv7                        9590 non-null   float64
 50  total_renewable_mu_cv7             9590 non-null   float64
 51  vre_ratio                          9590 non-null   float64
 52  re_7d_trend                        9590 non-null   float64
 53  failure                            9590 non-null   int64
dtypes: float64(43), int64(9), object(2)
memory usage: 4.0+ MB

In [11]:
df_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19330 entries, 0 to 19329
Data columns (total 54 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   date                               19330 non-null  object
 1   region                             19330 non-null  object
 2   wind_mu                            19330 non-null  float64
 3   hydro_mu                           19330 non-null  int64
 4   solar_mu                           19330 non-null  float64
 5   total_renewable_mu                 19330 non-null  float64
 6   day_of_week                        19330 non-null  int64
 7   month                              19330 non-null  int64
 8   quarter                            19330 non-null  int64
 9   day_of_year                        19330 non-null  int64
 10  is_monsoon                         19330 non-null  int64
 11  is_summer                          19330 non-null  int64
 12  is_winter                          19330 non-null  int64
 13  month_sin                          19330 non-null  float64
 14  month_cos                          19330 non-null  float64
 15  solar_mu_lag1                      19325 non-null  float64
 16  solar_mu_lag3                      19315 non-null  float64
 17  solar_mu_lag7                      19295 non-null  float64
 18  solar_mu_lag14                     19260 non-null  float64
 19  wind_mu_lag1                       19325 non-null  float64
 20  wind_mu_lag3                       19315 non-null  float64
 21  wind_mu_lag7                       19295 non-null  float64
 22  wind_mu_lag14                      19260 non-null  float64
 23  hydro_mu_lag1                      19325 non-null  float64
 24  hydro_mu_lag3                      19315 non-null  float64
 25  hydro_mu_lag7                      19295 non-null  float64
 26  hydro_mu_lag14                     19260 non-null  float64
 27  total_renewable_mu_lag1            19325 non-null  float64
 28  total_renewable_mu_lag3            19315 non-null  float64
 29  total_renewable_mu_lag7            19295 non-null  float64
 30  total_renewable_mu_lag14           19260 non-null  float64
 31  solar_mu_roll7_mean                19330 non-null  float64
 32  solar_mu_roll30_mean               19330 non-null  float64
 33  solar_mu_roll7_std                 19330 non-null  float64
 34  wind_mu_roll7_mean                 19330 non-null  float64
 35  wind_mu_roll30_mean                19330 non-null  float64
 36  wind_mu_roll7_std                  19330 non-null  float64
 37  hydro_mu_roll7_mean                19330 non-null  float64
 38  hydro_mu_roll30_mean               19330 non-null  float64
 39  hydro_mu_roll7_std                 19330 non-null  float64
 40  total_renewable_mu_roll7_mean      19330 non-null  float64
 41  total_renewable_mu_roll30_mean     19330 non-null  float64
 42  total_renewable_mu_roll7_std       19330 non-null  float64
 43  solar_mu_dev_from_avg              19330 non-null  float64
 44  wind_mu_dev_from_avg               19330 non-null  float64
 45  solar_mu_day_change_pct            19325 non-null  float64
 46  wind_mu_day_change_pct             19325 non-null  float64
 47  total_renewable_mu_day_change_pct  19325 non-null  float64
 48  solar_mu_cv7                       19330 non-null  float64
 49  wind_mu_cv7                        19330 non-null  float64
 50  total_renewable_mu_cv7             19330 non-null  float64
 51  vre_ratio                          19330 non-null  float64
 52  re_7d_trend                        19295 non-null  float64
 53  failure                            19330 non-null  int64
dtypes: float64(43), int64(9), object(2)
memory usage: 8.0+ MB